OLED_ENABLE = yes
OLED_DRIVER = SSD1306

ENCODER_ENABLE = yes
RGB_MATRIX_ENABLE = yes

CAPS_WORD_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes


#WPM_ENABLE = yes

NKRO_ENABLE = yes

# CONSOLE_ENABLE = yes

COMBO_ENABLE = no
COMMAND_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_KEYCODE_ENABLE = no

SRC += features/custom_shift_keys.c
